/**
 * Builds the Ontology 101 wine & food ontology from scratch, one okb command at a
 * time, and writes a transcript (examples/wine/TRANSCRIPT.md) showing every command
 * and its output. Read the transcript as a tutorial; run this script as an
 * end-to-end test (npm run example). It fails if the final ontology has errors.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const CLI = join(ROOT, "src", "cli.ts");
// Every date okb records in the example (created, decision dates) is this day, so
// rebuilding it gives identical files on any day and in any time zone.
const EXAMPLE_DATE = "2026-09-23";
const ENV = { ...process.env, NO_COLOR: "1", SOURCE_DATE_EPOCH: String(Date.parse(`${EXAMPLE_DATE}T00:00:00Z`) / 1000) };
const DIR = join(ROOT, "examples", "wine");

type Cmd = string[] | { note: string };
const md: string[] = [
  "# Worked example: the Ontology 101 wine & food ontology",
  "",
  "Generated by `npm run example` (examples/build-wine.ts). Every command below was really run, and the output under it is what okb printed.",
  "It follows the paper's running example. Where the paper leaves a detail open, the choice made here is recorded as a design decision.",
  "",
];

function run(args: string[], allowFail = false): string {
  try {
    return execFileSync(process.execPath, [CLI, ...args], { cwd: DIR, encoding: "utf8", env: ENV });
  } catch (e: any) {
    if (!allowFail) throw new Error(`okb ${args.join(" ")} failed:\n${e.stdout}${e.stderr}`);
    return (e.stdout ?? "") + (e.stderr ?? "");
  }
}

const q = (a: string) => (/[\s"'|=]/.test(a) && !/^[\w-]+(\+|-)?=/.test(a) ? JSON.stringify(a) : /^[\w-]+(\+|-)?=.*\s/.test(a) ? a.replace(/=(.*)$/, (_m, v) => `=${JSON.stringify(v)}`) : a);

function step(title: string, cmds: Cmd[], opts: { showOutput?: boolean; allowFail?: boolean } = {}) {
  md.push(`## ${title}`, "");
  for (const c of cmds) {
    if (!Array.isArray(c)) {
      md.push(c.note, "");
      continue;
    }
    const out = run(c, opts.allowFail).trimEnd();
    md.push("```console", `$ okb ${c.map(q).join(" ")}`);
    if (opts.showOutput !== false && out) md.push(out);
    md.push("```", "");
  }
}

rmSync(DIR, { recursive: true, force: true });
mkdirSync(dirname(DIR), { recursive: true });
execFileSync(process.execPath, [CLI, "init", DIR, "--name", "Wine and Food"], { encoding: "utf8", env: ENV });
md.push("```console", '$ okb init wine --name "Wine and Food"', "```", "");

step("Step 1: Scope and competency questions", [
  { note: "The paper's scope: wines, food, and which combinations are good. Inventory and staff are explicitly left out." },
  ["scope", "--domain", "Wines, foods, and which wines go well with which foods", "--purpose", "Suggest good wine and food combinations for a restaurant menu and answer diners' questions",
    "--users", "diners,waiters", "--maintainers", "sommelier", "--out-of-scope", "winery inventory", "--out-of-scope", "restaurant staff"],
  ["cq", "add", "Which wine characteristics should I consider when choosing a wine?"],
  ["cq", "add", "Is Bordeaux a red or white wine?"],
  ["cq", "add", "Does Cabernet Sauvignon go well with seafood?"],
  ["cq", "add", "What is the best choice of wine for grilled meat?"],
  ["cq", "add", "Which characteristics of a wine affect its appropriateness for a dish?"],
  ["cq", "add", "Which wines does a given winery produce?"],
  ["status"],
  ["step", "next"],
], { showOutput: true });

step("Step 2: Consider reuse", [
  { note: "The paper mentions existing wine vocabularies but deliberately builds from scratch to teach the method. We record that honestly." },
  ["reuse", "none", "--why", "Following Ontology 101, which builds the wine ontology from scratch for teaching; a French-wine knowledge base or retailer vocabulary would be candidates in a real project."],
  ["step", "next"],
], { showOutput: false });

step("Step 3: Brainstorm terms", [
  ["term", "add", "wine", "grape", "winery", "location", "color", "body", "flavor", "sugar", "tannin level", "red wine", "white wine", "rosé wine", "dessert wine", "port", "bordeaux", "beaujolais", "food", "seafood", "red meat", "goes well with", "vintage year", "label paper"],
  ["term", "list"],
  ["step", "next"],
], { showOutput: true });

step("Step 4: Classes and the hierarchy", [
  { note: "First a naming convention (the defaults), then classes. We work in the paper's 'combination' style: Wine at the top, the familiar color groups in the middle, and specific wines below." },
  ["convention"],
  ["class", "add", "Wine", "--desc", "A specific wine produced by a specific winery (not an individual bottle)."],
  ["class", "add", "Wines", "--parent", "Wine", "--force"],
  { note: "Even with --force, okb refuses 'Wines' as a subclass of 'Wine'. That's Ontology 101's classic singular/plural mistake (§4.1)." },
], { allowFail: true });
step("Step 4 (continued)", [
  ["class", "add", "RedWine", "--parent", "Wine", "--desc", "Wine made from dark-skinned grapes with skin contact; described by tannin level."],
  ["class", "add", "WhiteWine", "--parent", "Wine", "--desc", "Wine fermented without grape skins."],
  ["class", "add", "RoseWine", "--parent", "Wine", "--desc", "Wine with brief skin contact giving a pink color.", "--synonym", "Rosé"],
  ["class", "add", "DessertWine", "--parent", "Wine", "--desc", "Sweet wine served with or as dessert."],
  ["class", "disjoint", "RedWine", "WhiteWine", "RoseWine"],
  ["class", "add", "Bordeaux", "--parent", "RedWine", "--terminological", "--desc", "Red wine from the Bordeaux region of France."],
  ["class", "add", "Medoc", "--parent", "Bordeaux", "--terminological", "--desc", "Bordeaux from the Médoc sub-region."],
  ["class", "add", "Pauillac", "--parent", "Medoc", "--terminological", "--desc", "Médoc wine from the Pauillac appellation."],
  ["class", "add", "Margaux", "--parent", "Medoc", "--terminological", "--desc", "Médoc wine from the Margaux appellation."],
  ["class", "add", "Beaujolais", "--parent", "RedWine", "--terminological", "--desc", "Light red wine from the Beaujolais region, made from Gamay."],
  ["class", "add", "Merlot", "--parent", "RedWine", "--desc", "Red wine made from the Merlot grape."],
  ["class", "add", "Port", "--parent", "RedWine", "--parent", "DessertWine", "--desc", "Fortified sweet red wine from Portugal. (Only red Ports are modeled, as in the paper.)"],
  ["class", "add", "Chardonnay", "--parent", "WhiteWine", "--desc", "White wine made from the Chardonnay grape."],
  ["class", "add", "Riesling", "--parent", "WhiteWine", "--desc", "White wine made from the Riesling grape."],
  ["class", "disjoint", "Chardonnay", "Riesling"],
  ["class", "add", "Sauternes", "--parent", "WhiteWine", "--parent", "DessertWine", "--desc", "Sweet white wine from the Sauternes area of Bordeaux."],
  ["decision", "add", "--title", "Sauternes keeps its final s", "--decision", "The class is named Sauternes, not Sauterne.", "--why", "It's the proper name of the appellation, not a plural.", "--about", "Sauternes", "--waives", "naming-singular-plural-consistent"],
  ["class", "add", "Winery", "--desc", "A business that makes wine."],
  ["class", "add", "WineGrape", "--desc", "A grape variety used to make wine.", "--synonym", "Varietal"],
  ["class", "add", "WineRegion", "--desc", "A geographic area wines are named after or come from."],
  ["class", "add", "Food", "--abstract", "--desc", "A kind of dish or ingredient a wine can be paired with."],
  ["class", "add", "Seafood", "--parent", "Food", "--desc", "Fish and shellfish dishes."],
  ["class", "add", "RedMeat", "--parent", "Food", "--desc", "Beef, lamb and similar dishes, including grilled meat."],
  ["class", "disjoint", "Seafood", "RedMeat"],
  ["term", "set", "vintage year", "--as", "out-of-scope", "--note", "Vintage questions deferred to v2"],
  ["term", "set", "label paper", "--as", "out-of-scope"],
  ["term", "set", "port", "--as", "class", "--node", "Port"],
  ["term", "set", "rosé wine", "--as", "class", "--node", "RoseWine"],
  ["decision", "add", "--title", "Regional wines are terminological classes",
    "--decision", "Bordeaux, Medoc, Pauillac, Margaux and Beaujolais are classes even though they add no slots of their own.",
    "--why", "Sommeliers and diners always distinguish these appellations (Ontology 101 §4.4: distinctions experts commonly make).",
    "--about", "Bordeaux", "--about", "Medoc", "--about", "Beaujolais", "--waives", "hier-single-child"],
  ["tree"],
  ["validate"],
  ["step", "next"],
]);

step("Step 5: Slots", [
  { note: "The paper calls every attribute a *slot*. There are two kinds: **properties** hold a value, and **relationships** link to another thing and are stored as graph edges (`maker` → `:MAKER`). Slots go on the most general class whose members all have them, so tanninLevel goes on RedWine, not Wine (§3, Step 6)." },
  ["property", "add", "color", "--on", "Wine", "--type", "Enumerated", "--values", "red,white,rose", "--card", "single", "--desc", "The wine's color."],
  ["property", "add", "body", "--on", "Wine", "--type", "Enumerated", "--values", "light,medium,full", "--card", "single", "--desc", "How heavy the wine feels in the mouth."],
  ["property", "add", "flavor", "--on", "Wine", "--type", "Enumerated", "--values", "delicate,moderate,strong", "--card", "single", "--desc", "Intensity of the wine's flavor."],
  ["property", "add", "sugar", "--on", "Wine", "--type", "Enumerated", "--values", "dry,offDry,sweet", "--card", "single", "--desc", "Residual sweetness."],
  ["property", "add", "tanninLevel", "--on", "RedWine", "--type", "Enumerated", "--values", "low,moderate,high", "--card", "single", "--desc", "Astringency from grape skins; only meaningful for red wines."],
  ["relationship", "add", "maker", "--from", "Wine", "--to", "Winery", "--card", "single", "--min", "1", "--desc", "The winery that produced the wine."],
  ["relationship", "add", "produces", "--from", "Winery", "--to", "Wine", "--card", "multiple", "--desc", "Wines the winery makes."],
  ["relationship", "add", "grape", "--from", "Wine", "--to", "WineGrape", "--card", "multiple", "--min", "1", "--desc", "Grape varieties the wine is made from."],
  ["relationship", "add", "region", "--from", "Wine", "--to", "WineRegion", "--card", "single", "--desc", "Where the wine comes from."],
  ["property", "add", "location", "--on", "Winery", "--type", "String", "--card", "single", "--desc", "Where the winery is."],
  ["relationship", "add", "goesWellWith", "--from", "Wine", "--to", "Food", "--card", "multiple", "--desc", "Foods this wine pairs well with."],
  ["show", "RedWine"],
  ["step", "next"],
]);

step("Step 6: Facets, fixed values, inverses", [
  { note: "Fixed values are facts about a whole class. Every red wine's color is red, and every dessert wine is sweet (§5.2). A pairing stated on a class applies to all its members." },
  ["relationship", "inverse", "maker", "produces"],
  ["class", "fix", "RedWine", "color=red"],
  ["class", "fix", "WhiteWine", "color=white"],
  ["class", "fix", "RoseWine", "color=rose"],
  ["class", "fix", "DessertWine", "sugar=sweet"],
  ["class", "fix", "RedWine", "goesWellWith=RedMeat"],
  ["class", "fix", "WhiteWine", "goesWellWith=Seafood"],
  { note: "A pairing's strength belongs to the pairing itself, not to the wine or the food, so it's an **edge property** (see `okb explain decision.edge-or-class`)." },
  ["relationship", "property", "goesWellWith", "strength", "--type", "Enumerated", "--values", "classic,good"],
  ["link", "RedWine", "goesWellWith", "RedMeat", "strength=classic"],
  ["class", "default", "Wine", "body=medium"],
  ["validate"],
  ["step", "next"],
]);

step("Step 7: Instances", [
  { note: "The paper's instance (Figure 5), plus what it needs: its winery, grape and region. Grape-variety classes get their grape as a fixed value." },
  ["instance", "add", "Chateau Morgon", "--of", "Winery", "location=Beaujolais, France"],
  ["instance", "add", "Sterling Vineyards", "--of", "Winery", "location=Napa Valley, California"],
  ["instance", "add", "Gamay", "--of", "WineGrape"],
  ["instance", "add", "Merlot grape", "--of", "WineGrape"],
  ["instance", "add", "Chardonnay grape", "--of", "WineGrape"],
  ["instance", "add", "Riesling grape", "--of", "WineGrape"],
  ["instance", "add", "Beaujolais region", "--of", "WineRegion"],
  ["class", "fix", "Merlot", "grape=Merlot grape"],
  ["class", "fix", "Chardonnay", "grape=Chardonnay grape"],
  ["class", "fix", "Riesling", "grape=Riesling grape"],
  ["instance", "add", "Chateau Morgon Beaujolais", "--of", "Beaujolais", "body=light", "flavor=delicate", "tanninLevel=low", "grape=Gamay", "maker=Chateau Morgon", "region=Beaujolais region", "sugar=dry"],
  ["instance", "add", "Sterling Vineyards Merlot", "--of", "Merlot", "maker=Sterling Vineyards", "flavor=moderate", "tanninLevel=moderate", "sugar=dry"],
  ["show", "Chateau Morgon Beaujolais"],
  ["show", "Chateau Morgon"],
  { note: "Chateau Morgon `produces` Chateau Morgon Beaujolais without a second edge: `produces` is the inverse of `maker`, so it reads the single :MAKER edge backwards." },
  ["step", "next"],
]);

step("Step 8: Review against the questions", [
  { note: "Link each competency question to what answers it, then run every check." },
  ["cq", "link", "1", "color", "body", "flavor", "sugar", "tanninLevel"],
  ["cq", "link", "2", "Bordeaux", "RedWine", "WhiteWine"],
  ["cq", "link", "3", "goesWellWith", "grape", "Seafood"],
  ["cq", "link", "4", "RedMeat", "goesWellWith"],
  ["cq", "link", "5", "goesWellWith", "body", "flavor"],
  ["cq", "link", "6", "produces", "Winery"],
  ["cq", "list"],
  ["validate", "--all"],
  { note: "Four hints are left in on purpose so you can see what they look like. `WineRegion`, `region` and `location` aren't needed by any question yet (§4.7): either add a question like \"Where does this wine come from?\" or drop them. Two sibling groups have no disjointness declared. That's worth a real conversation: a Bordeaux blend usually contains Merlot grapes, so are the classes Merlot and Bordeaux disjoint? It depends on whether Merlot means 'varietal Merlot wine'. Record the answer as a design decision." },
  ["status"],
  ["diagram", "--out", "diagram.md"],
]);

step("Export for a graph database", [
  { note: "In the okb files, classes are nodes so the schema can be checked. A graph database usually wants the data the other way round: each instance becomes a node labeled with its class and all its ancestors, with properties (including fixed values inherited from classes) and typed relationships." },
  ["export", "--format", "cypher", "--out", "wine.cypher"],
  ["export", "--with-schema", "--out", "wine-export.json"],
]);

writeFileSync(join(DIR, "TRANSCRIPT.md"), md.join("\n") + "\n");
const final = JSON.parse(run(["validate", "--all", "--json"], true));
const errors = final.findings.filter((f: any) => f.severity === "error");
console.log(`Built examples/wine (${final.findings.length} finding(s), ${errors.length} error(s)). Transcript: examples/wine/TRANSCRIPT.md`);
if (errors.length) {
  for (const e of errors) console.error("  ✗", e.rule, e.message);
  process.exit(1);
}
